# Generated by Django 3.0.7 on 2020-07-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
